#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="/home/franka/massage/robots/fairino"
SCRIPT_PATH="$PROJECT_DIR/fairino_spring_assist.py"
DEFAULT_CONFIG_FILE="$PROJECT_DIR/fairino_spring.env"
CONFIG_FILE="${FAIRINO_SPRING_ENV:-$DEFAULT_CONFIG_FILE}"
CONFIG_FROM_CLI="0"
PRINT_CONFIG="0"
DRY_RUN="0"
PASSTHROUGH_ARGS=()

DEFAULT_ROBOT_IP="192.168.58.2"
DEFAULT_MODE_AUTO="1"
DEFAULT_ROBOT_ENABLE="1"
DEFAULT_SLEEP_AFTER_MODE_CMD="0.5"

DEFAULT_SENSOR_COMPANY="24"
DEFAULT_SENSOR_DEVICE="0"
DEFAULT_SENSOR_SOFTVERSION="0"
DEFAULT_SENSOR_BUS="1"
DEFAULT_SKIP_ZERO="0"
DEFAULT_SLEEP_AFTER_SENSOR_CMD="1.0"
DEFAULT_PAYLOAD_WEIGHT=""
DEFAULT_PAYLOAD_COG=""

DEFAULT_CONTROL_MODE="joint_drag"
DEFAULT_WORKSPACE="1"
DEFAULT_FORCE_THRESHOLD="80,80,4,8,8,8"
DEFAULT_MASS="2,2,0.8,0.2,0.2,0.2"
DEFAULT_DAMPING="120,120,35,2,2,2"
DEFAULT_STIFFNESS="1000,1000,20,80,80,80"
DEFAULT_MAX_V="60"
DEFAULT_MAX_VA="120"
DEFAULT_MAX_W="20"
DEFAULT_MAX_WA="40"

DEFAULT_DRAG_BACKEND="plain"
DEFAULT_DRAG_LAMBDA="3,2,2,2,2,3"
DEFAULT_DRAG_IMPEDANCE_FLAG="0"
DEFAULT_DRAG_K="0,0,0,0,0,0"
DEFAULT_DRAG_B="150,150,150,5,5,1"
DEFAULT_DRAG_MAX_TCP_VEL="1000"
DEFAULT_DRAG_MAX_TCP_ORI_VEL="180"
DEFAULT_DRAG_EXIT_TIMEOUT="5.0"
DEFAULT_DRAG_EXIT_POLL_INTERVAL="0.1"
DEFAULT_SLEEP_AFTER_DRAG_EXIT="1.0"
DEFAULT_TORQUE_SPRING_K="0.03,0.12,0.12,0.015,0.015,0.01"
DEFAULT_TORQUE_SPRING_D="0.004,0.02,0.02,0.002,0.002,0.001"
DEFAULT_TORQUE_SPRING_MAX_DELTA="0.8,3.0,3.0,0.5,0.5,0.3"
DEFAULT_TORQUE_SPRING_DEADBAND="0.2,0.2,0.2,0.1,0.1,0.1"
DEFAULT_TORQUE_LOOP_INTERVAL="0.008"
DEFAULT_TORQUE_CMD_TYPE="1"
DEFAULT_TORQUE_POWER_LIMIT="150"

DEFAULT_RETURN_ENABLED="1"
DEFAULT_RETURN_FORCE_THRESHOLD="1.5"
DEFAULT_RETURN_REACQUIRE_FORCE="30.0"
DEFAULT_RETURN_REACQUIRE_DELAY="1.0"
DEFAULT_RETURN_REACQUIRE_SPEED="6.0"
DEFAULT_RETURN_RELEASE_HOLD="0.5"
DEFAULT_RETURN_TRANSLATION_BAND="12.0"
DEFAULT_RETURN_ROTATION_BAND="4.0"
DEFAULT_RETURN_K_XYZ="0.08"
DEFAULT_RETURN_K_RPY="0.05"
DEFAULT_RETURN_MAX_STEP_XYZ="3.0"
DEFAULT_RETURN_MAX_STEP_RPY="0.6"
DEFAULT_RETURN_JOINT_K="0.25,0.35,0.35,0.18,0.18,0.12"
DEFAULT_RETURN_JOINT_MAX_STEP="0.6,1.0,1.0,0.4,0.4,0.3"
DEFAULT_RETURN_JOINT_BAND="1.0"
DEFAULT_RETURN_RELEASE_SPEED="1.2"
DEFAULT_RETURN_CMDT="0.008"
DEFAULT_RETURN_CMD_TYPE="1"

DEFAULT_HOLD_SECONDS="0"
DEFAULT_LOG_INTERVAL="0.2"

usage() {
  cat <<'USAGE_EOF'
用法:
  ./run_fairino_spring.sh
  ./run_fairino_spring.sh --config /path/to/site_a.env
  ./run_fairino_spring.sh --print-config
  ./run_fairino_spring.sh --dry-run

说明:
  - 这是“原位弹簧模拟 / 托举顺应”启动器
  - 默认读取 /home/franka/massage/robots/fairino/fairino_spring.env
  - 推荐先用 --print-config 和 --dry-run 检查
USAGE_EOF
}

choose_python() {
  if [[ -x "$PROJECT_DIR/.venv/bin/python" ]]; then
    echo "$PROJECT_DIR/.venv/bin/python"
    return 0
  fi
  if [[ -x "/home/franka/anaconda3/envs/llamauav/bin/python" ]]; then
    echo "/home/franka/anaconda3/envs/llamauav/bin/python"
    return 0
  fi
  if command -v python3 >/dev/null 2>&1; then
    command -v python3
    return 0
  fi
  return 1
}

is_truthy() {
  case "${1:-0}" in
    1|true|TRUE|yes|YES|on|ON|y|Y)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

append_if_nonempty() {
  local -n _cmd_ref="$1"
  local flag="$2"
  local value="$3"
  if [[ -n "$value" ]]; then
    _cmd_ref+=("$flag" "$value")
  fi
}

print_effective_config() {
  cat <<CONFIG_EOF
[SpringConfig]
CONFIG_FILE="$CONFIG_FILE"
ROBOT_IP="$ROBOT_IP"
MODE_AUTO="$MODE_AUTO"
ROBOT_ENABLE="$ROBOT_ENABLE"
SLEEP_AFTER_MODE_CMD="$SLEEP_AFTER_MODE_CMD"
SENSOR_COMPANY="$SENSOR_COMPANY"
SENSOR_DEVICE="$SENSOR_DEVICE"
SENSOR_SOFTVERSION="$SENSOR_SOFTVERSION"
SENSOR_BUS="$SENSOR_BUS"
SKIP_ZERO="$SKIP_ZERO"
SLEEP_AFTER_SENSOR_CMD="$SLEEP_AFTER_SENSOR_CMD"
PAYLOAD_WEIGHT="$PAYLOAD_WEIGHT"
PAYLOAD_COG="$PAYLOAD_COG"
WORKSPACE="$WORKSPACE"
CONTROL_MODE="$CONTROL_MODE"
FORCE_THRESHOLD="$FORCE_THRESHOLD"
MASS="$MASS"
DAMPING="$DAMPING"
STIFFNESS="$STIFFNESS"
MAX_V="$MAX_V"
MAX_VA="$MAX_VA"
MAX_W="$MAX_W"
MAX_WA="$MAX_WA"
DRAG_BACKEND="$DRAG_BACKEND"
DRAG_LAMBDA="$DRAG_LAMBDA"
TORQUE_SPRING_K="$TORQUE_SPRING_K"
TORQUE_SPRING_D="$TORQUE_SPRING_D"
TORQUE_SPRING_MAX_DELTA="$TORQUE_SPRING_MAX_DELTA"
TORQUE_SPRING_DEADBAND="$TORQUE_SPRING_DEADBAND"
TORQUE_LOOP_INTERVAL="$TORQUE_LOOP_INTERVAL"
TORQUE_CMD_TYPE="$TORQUE_CMD_TYPE"
TORQUE_POWER_LIMIT="$TORQUE_POWER_LIMIT"
DRAG_IMPEDANCE_FLAG="$DRAG_IMPEDANCE_FLAG"
DRAG_K="$DRAG_K"
DRAG_B="$DRAG_B"
DRAG_MAX_TCP_VEL="$DRAG_MAX_TCP_VEL"
DRAG_MAX_TCP_ORI_VEL="$DRAG_MAX_TCP_ORI_VEL"
DRAG_EXIT_TIMEOUT="$DRAG_EXIT_TIMEOUT"
DRAG_EXIT_POLL_INTERVAL="$DRAG_EXIT_POLL_INTERVAL"
SLEEP_AFTER_DRAG_EXIT="$SLEEP_AFTER_DRAG_EXIT"
RETURN_ENABLED="$RETURN_ENABLED"
RETURN_FORCE_THRESHOLD="$RETURN_FORCE_THRESHOLD"
RETURN_REACQUIRE_FORCE="$RETURN_REACQUIRE_FORCE"
RETURN_REACQUIRE_DELAY="$RETURN_REACQUIRE_DELAY"
RETURN_REACQUIRE_SPEED="$RETURN_REACQUIRE_SPEED"
RETURN_RELEASE_HOLD="$RETURN_RELEASE_HOLD"
RETURN_TRANSLATION_BAND="$RETURN_TRANSLATION_BAND"
RETURN_ROTATION_BAND="$RETURN_ROTATION_BAND"
RETURN_K_XYZ="$RETURN_K_XYZ"
RETURN_K_RPY="$RETURN_K_RPY"
RETURN_MAX_STEP_XYZ="$RETURN_MAX_STEP_XYZ"
RETURN_MAX_STEP_RPY="$RETURN_MAX_STEP_RPY"
RETURN_JOINT_K="$RETURN_JOINT_K"
RETURN_JOINT_MAX_STEP="$RETURN_JOINT_MAX_STEP"
RETURN_JOINT_BAND="$RETURN_JOINT_BAND"
RETURN_RELEASE_SPEED="$RETURN_RELEASE_SPEED"
RETURN_CMDT="$RETURN_CMDT"
RETURN_CMD_TYPE="$RETURN_CMD_TYPE"
HOLD_SECONDS="$HOLD_SECONDS"
LOG_INTERVAL="$LOG_INTERVAL"
CONFIG_EOF
}

if [[ ! -f "$SCRIPT_PATH" ]]; then
  echo "未找到脚本: $SCRIPT_PATH" >&2
  exit 1
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --config)
      if [[ $# -lt 2 ]]; then
        echo "--config 需要一个文件路径" >&2
        exit 1
      fi
      CONFIG_FILE="$2"
      CONFIG_FROM_CLI="1"
      shift 2
      ;;
    --print-config)
      PRINT_CONFIG="1"
      shift
      ;;
    --dry-run)
      DRY_RUN="1"
      shift
      ;;
    *)
      PASSTHROUGH_ARGS+=("$1")
      shift
      ;;
  esac
done

if [[ "$CONFIG_FROM_CLI" == "1" && ! -f "$CONFIG_FILE" ]]; then
  echo "指定的配置文件不存在: $CONFIG_FILE" >&2
  exit 1
fi

if [[ -n "${FAIRINO_SPRING_ENV:-}" && ! -f "$CONFIG_FILE" ]]; then
  echo "FAIRINO_SPRING_ENV 指向的配置文件不存在: $CONFIG_FILE" >&2
  exit 1
fi

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

ROBOT_IP="${ROBOT_IP:-$DEFAULT_ROBOT_IP}"
MODE_AUTO="${MODE_AUTO:-$DEFAULT_MODE_AUTO}"
ROBOT_ENABLE="${ROBOT_ENABLE:-$DEFAULT_ROBOT_ENABLE}"
SLEEP_AFTER_MODE_CMD="${SLEEP_AFTER_MODE_CMD:-$DEFAULT_SLEEP_AFTER_MODE_CMD}"

SENSOR_COMPANY="${SENSOR_COMPANY:-$DEFAULT_SENSOR_COMPANY}"
SENSOR_DEVICE="${SENSOR_DEVICE:-$DEFAULT_SENSOR_DEVICE}"
SENSOR_SOFTVERSION="${SENSOR_SOFTVERSION:-$DEFAULT_SENSOR_SOFTVERSION}"
SENSOR_BUS="${SENSOR_BUS:-$DEFAULT_SENSOR_BUS}"
SKIP_ZERO="${SKIP_ZERO:-$DEFAULT_SKIP_ZERO}"
SLEEP_AFTER_SENSOR_CMD="${SLEEP_AFTER_SENSOR_CMD:-$DEFAULT_SLEEP_AFTER_SENSOR_CMD}"
PAYLOAD_WEIGHT="${PAYLOAD_WEIGHT:-$DEFAULT_PAYLOAD_WEIGHT}"
PAYLOAD_COG="${PAYLOAD_COG:-$DEFAULT_PAYLOAD_COG}"

CONTROL_MODE="${CONTROL_MODE:-$DEFAULT_CONTROL_MODE}"
WORKSPACE="${WORKSPACE:-$DEFAULT_WORKSPACE}"
FORCE_THRESHOLD="${FORCE_THRESHOLD:-$DEFAULT_FORCE_THRESHOLD}"
MASS="${MASS:-$DEFAULT_MASS}"
DAMPING="${DAMPING:-$DEFAULT_DAMPING}"
STIFFNESS="${STIFFNESS:-$DEFAULT_STIFFNESS}"
MAX_V="${MAX_V:-$DEFAULT_MAX_V}"
MAX_VA="${MAX_VA:-$DEFAULT_MAX_VA}"
MAX_W="${MAX_W:-$DEFAULT_MAX_W}"
MAX_WA="${MAX_WA:-$DEFAULT_MAX_WA}"

DRAG_BACKEND="${DRAG_BACKEND:-$DEFAULT_DRAG_BACKEND}"
DRAG_LAMBDA="${DRAG_LAMBDA:-$DEFAULT_DRAG_LAMBDA}"
TORQUE_SPRING_K="${TORQUE_SPRING_K:-$DEFAULT_TORQUE_SPRING_K}"
TORQUE_SPRING_D="${TORQUE_SPRING_D:-$DEFAULT_TORQUE_SPRING_D}"
TORQUE_SPRING_MAX_DELTA="${TORQUE_SPRING_MAX_DELTA:-$DEFAULT_TORQUE_SPRING_MAX_DELTA}"
TORQUE_SPRING_DEADBAND="${TORQUE_SPRING_DEADBAND:-$DEFAULT_TORQUE_SPRING_DEADBAND}"
TORQUE_LOOP_INTERVAL="${TORQUE_LOOP_INTERVAL:-$DEFAULT_TORQUE_LOOP_INTERVAL}"
TORQUE_CMD_TYPE="${TORQUE_CMD_TYPE:-$DEFAULT_TORQUE_CMD_TYPE}"
TORQUE_POWER_LIMIT="${TORQUE_POWER_LIMIT:-$DEFAULT_TORQUE_POWER_LIMIT}"
DRAG_IMPEDANCE_FLAG="${DRAG_IMPEDANCE_FLAG:-$DEFAULT_DRAG_IMPEDANCE_FLAG}"
DRAG_K="${DRAG_K:-$DEFAULT_DRAG_K}"
DRAG_B="${DRAG_B:-$DEFAULT_DRAG_B}"
DRAG_MAX_TCP_VEL="${DRAG_MAX_TCP_VEL:-$DEFAULT_DRAG_MAX_TCP_VEL}"
DRAG_MAX_TCP_ORI_VEL="${DRAG_MAX_TCP_ORI_VEL:-$DEFAULT_DRAG_MAX_TCP_ORI_VEL}"
DRAG_EXIT_TIMEOUT="${DRAG_EXIT_TIMEOUT:-$DEFAULT_DRAG_EXIT_TIMEOUT}"
DRAG_EXIT_POLL_INTERVAL="${DRAG_EXIT_POLL_INTERVAL:-$DEFAULT_DRAG_EXIT_POLL_INTERVAL}"
SLEEP_AFTER_DRAG_EXIT="${SLEEP_AFTER_DRAG_EXIT:-$DEFAULT_SLEEP_AFTER_DRAG_EXIT}"

RETURN_ENABLED="${RETURN_ENABLED:-$DEFAULT_RETURN_ENABLED}"
RETURN_FORCE_THRESHOLD="${RETURN_FORCE_THRESHOLD:-$DEFAULT_RETURN_FORCE_THRESHOLD}"
RETURN_REACQUIRE_FORCE="${RETURN_REACQUIRE_FORCE:-$DEFAULT_RETURN_REACQUIRE_FORCE}"
RETURN_REACQUIRE_DELAY="${RETURN_REACQUIRE_DELAY:-$DEFAULT_RETURN_REACQUIRE_DELAY}"
RETURN_REACQUIRE_SPEED="${RETURN_REACQUIRE_SPEED:-$DEFAULT_RETURN_REACQUIRE_SPEED}"
RETURN_RELEASE_HOLD="${RETURN_RELEASE_HOLD:-$DEFAULT_RETURN_RELEASE_HOLD}"
RETURN_TRANSLATION_BAND="${RETURN_TRANSLATION_BAND:-$DEFAULT_RETURN_TRANSLATION_BAND}"
RETURN_ROTATION_BAND="${RETURN_ROTATION_BAND:-$DEFAULT_RETURN_ROTATION_BAND}"
RETURN_K_XYZ="${RETURN_K_XYZ:-$DEFAULT_RETURN_K_XYZ}"
RETURN_K_RPY="${RETURN_K_RPY:-$DEFAULT_RETURN_K_RPY}"
RETURN_MAX_STEP_XYZ="${RETURN_MAX_STEP_XYZ:-$DEFAULT_RETURN_MAX_STEP_XYZ}"
RETURN_MAX_STEP_RPY="${RETURN_MAX_STEP_RPY:-$DEFAULT_RETURN_MAX_STEP_RPY}"
RETURN_JOINT_K="${RETURN_JOINT_K:-$DEFAULT_RETURN_JOINT_K}"
RETURN_JOINT_MAX_STEP="${RETURN_JOINT_MAX_STEP:-$DEFAULT_RETURN_JOINT_MAX_STEP}"
RETURN_JOINT_BAND="${RETURN_JOINT_BAND:-$DEFAULT_RETURN_JOINT_BAND}"
RETURN_RELEASE_SPEED="${RETURN_RELEASE_SPEED:-$DEFAULT_RETURN_RELEASE_SPEED}"
RETURN_CMDT="${RETURN_CMDT:-$DEFAULT_RETURN_CMDT}"
RETURN_CMD_TYPE="${RETURN_CMD_TYPE:-$DEFAULT_RETURN_CMD_TYPE}"

HOLD_SECONDS="${HOLD_SECONDS:-$DEFAULT_HOLD_SECONDS}"
LOG_INTERVAL="${LOG_INTERVAL:-$DEFAULT_LOG_INTERVAL}"

if [[ "$PRINT_CONFIG" == "1" ]]; then
  print_effective_config
  exit 0
fi

if ! PYTHON_BIN="$(choose_python)"; then
  echo "未找到可用的 Python 解释器" >&2
  exit 1
fi

cd "$PROJECT_DIR"

cmd=(
  "$PYTHON_BIN"
  "$SCRIPT_PATH"
  --ip "$ROBOT_IP"
  --sleep-after-mode-cmd "$SLEEP_AFTER_MODE_CMD"
  --sensor-company "$SENSOR_COMPANY"
  --sensor-device "$SENSOR_DEVICE"
  --sensor-softversion "$SENSOR_SOFTVERSION"
  --sensor-bus "$SENSOR_BUS"
  --sleep-after-sensor-cmd "$SLEEP_AFTER_SENSOR_CMD"
  --control-mode "$CONTROL_MODE"
  --workspace "$WORKSPACE"
  --force-threshold "$FORCE_THRESHOLD"
  --mass "$MASS"
  --damping "$DAMPING"
  --stiffness "$STIFFNESS"
  --max-v "$MAX_V"
  --max-va "$MAX_VA"
  --max-w "$MAX_W"
  --max-wa "$MAX_WA"
  --drag-backend "$DRAG_BACKEND"
  --drag-lambda "$DRAG_LAMBDA"
  --torque-spring-k "$TORQUE_SPRING_K"
  --torque-spring-d "$TORQUE_SPRING_D"
  --torque-spring-max-delta "$TORQUE_SPRING_MAX_DELTA"
  --torque-spring-deadband "$TORQUE_SPRING_DEADBAND"
  --torque-loop-interval "$TORQUE_LOOP_INTERVAL"
  --torque-cmd-type "$TORQUE_CMD_TYPE"
  --torque-power-limit "$TORQUE_POWER_LIMIT"
  --drag-impedance-flag "$DRAG_IMPEDANCE_FLAG"
  --drag-k "$DRAG_K"
  --drag-b "$DRAG_B"
  --drag-max-tcp-vel "$DRAG_MAX_TCP_VEL"
  --drag-max-tcp-ori-vel "$DRAG_MAX_TCP_ORI_VEL"
  --drag-exit-timeout "$DRAG_EXIT_TIMEOUT"
  --drag-exit-poll-interval "$DRAG_EXIT_POLL_INTERVAL"
  --sleep-after-drag-exit "$SLEEP_AFTER_DRAG_EXIT"
  --return-enabled "$RETURN_ENABLED"
  --return-force-threshold "$RETURN_FORCE_THRESHOLD"
  --return-reacquire-force "$RETURN_REACQUIRE_FORCE"
  --return-reacquire-delay "$RETURN_REACQUIRE_DELAY"
  --return-reacquire-speed "$RETURN_REACQUIRE_SPEED"
  --return-release-hold "$RETURN_RELEASE_HOLD"
  --return-translation-band "$RETURN_TRANSLATION_BAND"
  --return-rotation-band "$RETURN_ROTATION_BAND"
  --return-k-xyz "$RETURN_K_XYZ"
  --return-k-rpy "$RETURN_K_RPY"
  --return-max-step-xyz "$RETURN_MAX_STEP_XYZ"
  --return-max-step-rpy "$RETURN_MAX_STEP_RPY"
  --return-joint-k "$RETURN_JOINT_K"
  --return-joint-max-step "$RETURN_JOINT_MAX_STEP"
  --return-joint-band "$RETURN_JOINT_BAND"
  --return-release-speed "$RETURN_RELEASE_SPEED"
  --return-cmdt "$RETURN_CMDT"
  --return-cmd-type "$RETURN_CMD_TYPE"
  --hold-seconds "$HOLD_SECONDS"
  --log-interval "$LOG_INTERVAL"
)

append_if_nonempty cmd --payload-weight "$PAYLOAD_WEIGHT"
append_if_nonempty cmd --payload-cog "$PAYLOAD_COG"

if is_truthy "$MODE_AUTO"; then
  cmd+=(--mode-auto)
fi

if is_truthy "$ROBOT_ENABLE"; then
  cmd+=(--enable)
fi

if is_truthy "$SKIP_ZERO"; then
  cmd+=(--skip-zero)
fi

if [[ "${#PASSTHROUGH_ARGS[@]}" -gt 0 ]]; then
  cmd+=("${PASSTHROUGH_ARGS[@]}")
fi

if [[ "$DRY_RUN" == "1" ]]; then
  print_effective_config
  printf '[DryRun] '
  printf '%q ' "${cmd[@]}"
  printf '\n'
  exit 0
fi

exec "${cmd[@]}"
