# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/ArrayMsgGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class ArrayMsgGoal(genpy.Message):
  _md5sum = "b270891495ac7e0754cef9c5f82da8e8"
  _type = "rm_healthcare_robot_msgs/ArrayMsgGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal
PixelCoor[2] diagonal_point_coor   # 轮廓左上角和右下角的像素坐标
PixelCoor[] waypoints_pixel_coor   # 关键点的像素坐标数组

================================================================================
MSG: rm_healthcare_robot_msgs/PixelCoor
int16 x
int16 y"""
  __slots__ = ['diagonal_point_coor','waypoints_pixel_coor']
  _slot_types = ['rm_healthcare_robot_msgs/PixelCoor[2]','rm_healthcare_robot_msgs/PixelCoor[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       diagonal_point_coor,waypoints_pixel_coor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArrayMsgGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.diagonal_point_coor is None:
        self.diagonal_point_coor = [rm_healthcare_robot_msgs.msg.PixelCoor() for _ in range(2)]
      if self.waypoints_pixel_coor is None:
        self.waypoints_pixel_coor = []
    else:
      self.diagonal_point_coor = [rm_healthcare_robot_msgs.msg.PixelCoor() for _ in range(2)]
      self.waypoints_pixel_coor = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      if len(self.diagonal_point_coor) != 2:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (2, len(self.diagonal_point_coor), 'self.diagonal_point_coor')))
      for val1 in self.diagonal_point_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
      length = len(self.waypoints_pixel_coor)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints_pixel_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.diagonal_point_coor is None:
        self.diagonal_point_coor = None
      if self.waypoints_pixel_coor is None:
        self.waypoints_pixel_coor = None
      end = 0
      self.diagonal_point_coor = []
      for i in range(0, 2):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.diagonal_point_coor.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints_pixel_coor = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.waypoints_pixel_coor.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      if len(self.diagonal_point_coor) != 2:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (2, len(self.diagonal_point_coor), 'self.diagonal_point_coor')))
      for val1 in self.diagonal_point_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
      length = len(self.waypoints_pixel_coor)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints_pixel_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.diagonal_point_coor is None:
        self.diagonal_point_coor = None
      if self.waypoints_pixel_coor is None:
        self.waypoints_pixel_coor = None
      end = 0
      self.diagonal_point_coor = []
      for i in range(0, 2):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.diagonal_point_coor.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints_pixel_coor = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.waypoints_pixel_coor.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
