# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/Vip_Course_Node.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Vip_Course_Node(genpy.Message):
  _md5sum = "e93e9a01950cf61634301b955893cbfd"
  _type = "rm_healthcare_robot_msgs/Vip_Course_Node"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 acupoint_id
string acupoint_name
float32[7] pose     # x y z, x y z w
int32 technique_id
int32 time
int32 strength
int32 temp
int32 speed"""
  __slots__ = ['acupoint_id','acupoint_name','pose','technique_id','time','strength','temp','speed']
  _slot_types = ['int32','string','float32[7]','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       acupoint_id,acupoint_name,pose,technique_id,time,strength,temp,speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Vip_Course_Node, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.acupoint_id is None:
        self.acupoint_id = 0
      if self.acupoint_name is None:
        self.acupoint_name = ''
      if self.pose is None:
        self.pose = [0.] * 7
      if self.technique_id is None:
        self.technique_id = 0
      if self.time is None:
        self.time = 0
      if self.strength is None:
        self.strength = 0
      if self.temp is None:
        self.temp = 0
      if self.speed is None:
        self.speed = 0
    else:
      self.acupoint_id = 0
      self.acupoint_name = ''
      self.pose = [0.] * 7
      self.technique_id = 0
      self.time = 0
      self.strength = 0
      self.temp = 0
      self.speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.acupoint_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.acupoint_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_7f().pack(*self.pose))
      _x = self
      buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.acupoint_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.acupoint_name = str[start:end]
      start = end
      end += 28
      self.pose = _get_struct_7f().unpack(str[start:end])
      _x = self
      start = end
      end += 20
      (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.acupoint_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.acupoint_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.pose.tostring())
      _x = self
      buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.acupoint_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.acupoint_name = str[start:end]
      start = end
      end += 28
      self.pose = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
      _x = self
      start = end
      end += 20
      (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
