# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Force_Position_New.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Force_Position_New(genpy.Message):
  _md5sum = "170c2ba898b3cea7d9564f74070a4110"
  _type = "rm_msgs/Force_Position_New"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 sensor    # 0：一维力; 1：六维力
uint8 coordinate    # 0：工作坐标系力控; 1：工具坐标系力控  按摩默认为1
uint8 z_control_mode    # Z方向的控制模式; 0：力跟踪模式（穴位类包括定制项目采用该模式）; 1：力跟踪模式+姿态自适应模式（标准推揉型项目采用该模式）
int16 force # 力度"""
  __slots__ = ['sensor','coordinate','z_control_mode','force']
  _slot_types = ['uint8','uint8','uint8','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sensor,coordinate,z_control_mode,force

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Force_Position_New, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sensor is None:
        self.sensor = 0
      if self.coordinate is None:
        self.coordinate = 0
      if self.z_control_mode is None:
        self.z_control_mode = 0
      if self.force is None:
        self.force = 0
    else:
      self.sensor = 0
      self.coordinate = 0
      self.z_control_mode = 0
      self.force = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3Bh().pack(_x.sensor, _x.coordinate, _x.z_control_mode, _x.force))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sensor, _x.coordinate, _x.z_control_mode, _x.force,) = _get_struct_3Bh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3Bh().pack(_x.sensor, _x.coordinate, _x.z_control_mode, _x.force))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sensor, _x.coordinate, _x.z_control_mode, _x.force,) = _get_struct_3Bh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3Bh = None
def _get_struct_3Bh():
    global _struct_3Bh
    if _struct_3Bh is None:
        _struct_3Bh = struct.Struct("<3Bh")
    return _struct_3Bh
