# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/MoveL.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class MoveL(genpy.Message):
  _md5sum = "71f8a77c6be4dc679da6e3cd77730408"
  _type = "rm_msgs/MoveL"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose Pose
float32 speed
uint8 trajectory_connect

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['Pose','speed','trajectory_connect']
  _slot_types = ['geometry_msgs/Pose','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Pose,speed,trajectory_connect

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveL, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Pose is None:
        self.Pose = geometry_msgs.msg.Pose()
      if self.speed is None:
        self.speed = 0.
      if self.trajectory_connect is None:
        self.trajectory_connect = 0
    else:
      self.Pose = geometry_msgs.msg.Pose()
      self.speed = 0.
      self.trajectory_connect = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7dfB().pack(_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.speed, _x.trajectory_connect))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Pose is None:
        self.Pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.speed, _x.trajectory_connect,) = _get_struct_7dfB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7dfB().pack(_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.speed, _x.trajectory_connect))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Pose is None:
        self.Pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.speed, _x.trajectory_connect,) = _get_struct_7dfB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dfB = None
def _get_struct_7dfB():
    global _struct_7dfB
    if _struct_7dfB is None:
        _struct_7dfB = struct.Struct("<7dfB")
    return _struct_7dfB
