# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/AcupointCalcRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class AcupointCalcRequest(genpy.Message):
  _md5sum = "ebe008311517b20bfe1c9fc6213d9ef8"
  _type = "rm_healthcare_robot_msgs/AcupointCalcRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PixelCoor[] known_acupoint_p2d    # 识别的穴位二维像素坐标数组(需按照指定顺序)

================================================================================
MSG: rm_healthcare_robot_msgs/PixelCoor
int16 x
int16 y"""
  __slots__ = ['known_acupoint_p2d']
  _slot_types = ['rm_healthcare_robot_msgs/PixelCoor[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       known_acupoint_p2d

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AcupointCalcRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.known_acupoint_p2d is None:
        self.known_acupoint_p2d = []
    else:
      self.known_acupoint_p2d = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.known_acupoint_p2d)
      buff.write(_struct_I.pack(length))
      for val1 in self.known_acupoint_p2d:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.known_acupoint_p2d is None:
        self.known_acupoint_p2d = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.known_acupoint_p2d = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.known_acupoint_p2d.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.known_acupoint_p2d)
      buff.write(_struct_I.pack(length))
      for val1 in self.known_acupoint_p2d:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.known_acupoint_p2d is None:
        self.known_acupoint_p2d = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.known_acupoint_p2d = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.known_acupoint_p2d.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/AcupointCalcResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class AcupointCalcResponse(genpy.Message):
  _md5sum = "31f04671d4d771e75689ed60edb0ab4a"
  _type = "rm_healthcare_robot_msgs/AcupointCalcResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Acupoint[] acupoints    # 所有穴位(已识别+推算)

================================================================================
MSG: rm_healthcare_robot_msgs/Acupoint
string name # 穴位名
PixelCoor p2d   # 像素坐标
================================================================================
MSG: rm_healthcare_robot_msgs/PixelCoor
int16 x
int16 y"""
  __slots__ = ['acupoints']
  _slot_types = ['rm_healthcare_robot_msgs/Acupoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       acupoints

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AcupointCalcResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.acupoints is None:
        self.acupoints = []
    else:
      self.acupoints = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.acupoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.acupoints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v1 = val1.p2d
        _x = _v1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.acupoints is None:
        self.acupoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.acupoints = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Acupoint()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _v2 = val1.p2d
        _x = _v2
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.acupoints.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.acupoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.acupoints:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.p2d
        _x = _v3
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.acupoints is None:
        self.acupoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.acupoints = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Acupoint()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _v4 = val1.p2d
        _x = _v4
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.acupoints.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
class AcupointCalc(object):
  _type          = 'rm_healthcare_robot_msgs/AcupointCalc'
  _md5sum = 'bd26d8055aa110e19ee8331d97aa0f7d'
  _request_class  = AcupointCalcRequest
  _response_class = AcupointCalcResponse
