# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/get_camera_parameter_SrvRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class get_camera_parameter_SrvRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "rm_healthcare_robot_msgs/get_camera_parameter_SrvRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 获取相机参数
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(get_camera_parameter_SrvRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/get_camera_parameter_SrvResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class get_camera_parameter_SrvResponse(genpy.Message):
  _md5sum = "ca29ea56acbee05342e89647d6950cc6"
  _type = "rm_healthcare_robot_msgs/get_camera_parameter_SrvResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 color_fx 
float64 color_fy
float64 color_ppx
float64 color_ppy
int32 color_height
int32 color_width
float64 depth_fx 
float64 depth_fy
float64 depth_ppx
float64 depth_ppy
int32 depth_height
int32 depth_width
float64 depth_scale

"""
  __slots__ = ['color_fx','color_fy','color_ppx','color_ppy','color_height','color_width','depth_fx','depth_fy','depth_ppx','depth_ppy','depth_height','depth_width','depth_scale']
  _slot_types = ['float64','float64','float64','float64','int32','int32','float64','float64','float64','float64','int32','int32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       color_fx,color_fy,color_ppx,color_ppy,color_height,color_width,depth_fx,depth_fy,depth_ppx,depth_ppy,depth_height,depth_width,depth_scale

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(get_camera_parameter_SrvResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.color_fx is None:
        self.color_fx = 0.
      if self.color_fy is None:
        self.color_fy = 0.
      if self.color_ppx is None:
        self.color_ppx = 0.
      if self.color_ppy is None:
        self.color_ppy = 0.
      if self.color_height is None:
        self.color_height = 0
      if self.color_width is None:
        self.color_width = 0
      if self.depth_fx is None:
        self.depth_fx = 0.
      if self.depth_fy is None:
        self.depth_fy = 0.
      if self.depth_ppx is None:
        self.depth_ppx = 0.
      if self.depth_ppy is None:
        self.depth_ppy = 0.
      if self.depth_height is None:
        self.depth_height = 0
      if self.depth_width is None:
        self.depth_width = 0
      if self.depth_scale is None:
        self.depth_scale = 0.
    else:
      self.color_fx = 0.
      self.color_fy = 0.
      self.color_ppx = 0.
      self.color_ppy = 0.
      self.color_height = 0
      self.color_width = 0
      self.depth_fx = 0.
      self.depth_fy = 0.
      self.depth_ppx = 0.
      self.depth_ppy = 0.
      self.depth_height = 0
      self.depth_width = 0
      self.depth_scale = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d2i4d2id().pack(_x.color_fx, _x.color_fy, _x.color_ppx, _x.color_ppy, _x.color_height, _x.color_width, _x.depth_fx, _x.depth_fy, _x.depth_ppx, _x.depth_ppy, _x.depth_height, _x.depth_width, _x.depth_scale))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 88
      (_x.color_fx, _x.color_fy, _x.color_ppx, _x.color_ppy, _x.color_height, _x.color_width, _x.depth_fx, _x.depth_fy, _x.depth_ppx, _x.depth_ppy, _x.depth_height, _x.depth_width, _x.depth_scale,) = _get_struct_4d2i4d2id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d2i4d2id().pack(_x.color_fx, _x.color_fy, _x.color_ppx, _x.color_ppy, _x.color_height, _x.color_width, _x.depth_fx, _x.depth_fy, _x.depth_ppx, _x.depth_ppy, _x.depth_height, _x.depth_width, _x.depth_scale))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 88
      (_x.color_fx, _x.color_fy, _x.color_ppx, _x.color_ppy, _x.color_height, _x.color_width, _x.depth_fx, _x.depth_fy, _x.depth_ppx, _x.depth_ppy, _x.depth_height, _x.depth_width, _x.depth_scale,) = _get_struct_4d2i4d2id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d2i4d2id = None
def _get_struct_4d2i4d2id():
    global _struct_4d2i4d2id
    if _struct_4d2i4d2id is None:
        _struct_4d2i4d2id = struct.Struct("<4d2i4d2id")
    return _struct_4d2i4d2id
class get_camera_parameter_Srv(object):
  _type          = 'rm_healthcare_robot_msgs/get_camera_parameter_Srv'
  _md5sum = 'ca29ea56acbee05342e89647d6950cc6'
  _request_class  = get_camera_parameter_SrvRequest
  _response_class = get_camera_parameter_SrvResponse
