# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/Inverse_KinematicsRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import rm_healthcare_robot_msgs.msg

class Inverse_KinematicsRequest(genpy.Message):
  _md5sum = "b473a72cae9bf7fffdc1f89a9ac92832"
  _type = "rm_healthcare_robot_msgs/Inverse_KinematicsRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Kinematics_Pose_Node[] inverse
Kinematics_Joints_Node[] forward

================================================================================
MSG: rm_healthcare_robot_msgs/Kinematics_Pose_Node
geometry_msgs/Pose pose
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: rm_healthcare_robot_msgs/Kinematics_Joints_Node
float32[6] joints"""
  __slots__ = ['inverse','forward']
  _slot_types = ['rm_healthcare_robot_msgs/Kinematics_Pose_Node[]','rm_healthcare_robot_msgs/Kinematics_Joints_Node[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       inverse,forward

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Inverse_KinematicsRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.inverse is None:
        self.inverse = []
      if self.forward is None:
        self.forward = []
    else:
      self.inverse = []
      self.forward = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.inverse)
      buff.write(_struct_I.pack(length))
      for val1 in self.inverse:
        _v1 = val1.pose
        _v2 = _v1.position
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v3 = _v1.orientation
        _x = _v3
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      length = len(self.forward)
      buff.write(_struct_I.pack(length))
      for val1 in self.forward:
        buff.write(_get_struct_6f().pack(*val1.joints))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.inverse is None:
        self.inverse = None
      if self.forward is None:
        self.forward = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.inverse = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Kinematics_Pose_Node()
        _v4 = val1.pose
        _v5 = _v4.position
        _x = _v5
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v6 = _v4.orientation
        _x = _v6
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.inverse.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.forward = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Kinematics_Joints_Node()
        start = end
        end += 24
        val1.joints = _get_struct_6f().unpack(str[start:end])
        self.forward.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.inverse)
      buff.write(_struct_I.pack(length))
      for val1 in self.inverse:
        _v7 = val1.pose
        _v8 = _v7.position
        _x = _v8
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v9 = _v7.orientation
        _x = _v9
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      length = len(self.forward)
      buff.write(_struct_I.pack(length))
      for val1 in self.forward:
        buff.write(val1.joints.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.inverse is None:
        self.inverse = None
      if self.forward is None:
        self.forward = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.inverse = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Kinematics_Pose_Node()
        _v10 = val1.pose
        _v11 = _v10.position
        _x = _v11
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v12 = _v10.orientation
        _x = _v12
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.inverse.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.forward = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Kinematics_Joints_Node()
        start = end
        end += 24
        val1.joints = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=6)
        self.forward.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/Inverse_KinematicsResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class Inverse_KinematicsResponse(genpy.Message):
  _md5sum = "9df9f8293c6a753c77c18a1128dc093a"
  _type = "rm_healthcare_robot_msgs/Inverse_KinematicsResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Kinematics_Joints_Node[] forward
bool state


================================================================================
MSG: rm_healthcare_robot_msgs/Kinematics_Joints_Node
float32[6] joints"""
  __slots__ = ['forward','state']
  _slot_types = ['rm_healthcare_robot_msgs/Kinematics_Joints_Node[]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       forward,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Inverse_KinematicsResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.forward is None:
        self.forward = []
      if self.state is None:
        self.state = False
    else:
      self.forward = []
      self.state = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.forward)
      buff.write(_struct_I.pack(length))
      for val1 in self.forward:
        buff.write(_get_struct_6f().pack(*val1.joints))
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.forward is None:
        self.forward = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.forward = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Kinematics_Joints_Node()
        start = end
        end += 24
        val1.joints = _get_struct_6f().unpack(str[start:end])
        self.forward.append(val1)
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      self.state = bool(self.state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.forward)
      buff.write(_struct_I.pack(length))
      for val1 in self.forward:
        buff.write(val1.joints.tostring())
      _x = self.state
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.forward is None:
        self.forward = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.forward = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Kinematics_Joints_Node()
        start = end
        end += 24
        val1.joints = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=6)
        self.forward.append(val1)
      start = end
      end += 1
      (self.state,) = _get_struct_B().unpack(str[start:end])
      self.state = bool(self.state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class Inverse_Kinematics(object):
  _type          = 'rm_healthcare_robot_msgs/Inverse_Kinematics'
  _md5sum = 'f917b39992f3d3565dd3ea5de14c9c21'
  _request_class  = Inverse_KinematicsRequest
  _response_class = Inverse_KinematicsResponse
