# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/Operate_CourseRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class Operate_CourseRequest(genpy.Message):
  _md5sum = "fd290af9d53563efad658201ac4c05a6"
  _type = "rm_healthcare_robot_msgs/Operate_CourseRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#
string cmd                  # get add mod del

string course_label         # standard keynote vip drag

string old_course_name      # 用于修改课程，如果修改课程名字，此处填写原有的课程名字

Keynote_Course keynote_course   #用来添加和修改重点课程

Vip_Course vip_course               #用来添加和修改vip课程


================================================================================
MSG: rm_healthcare_robot_msgs/Keynote_Course
string course_name
int32 date_time
int32 tool_num

Keynote_Course_Node[] nodes

================================================================================
MSG: rm_healthcare_robot_msgs/Keynote_Course_Node
int32 acupoint_id
string acupoint_name
int32 technique_id
int32 time
int32 strength
int32 temp
int32 speed
================================================================================
MSG: rm_healthcare_robot_msgs/Vip_Course
# 仅用于vip课程中拖动定位课程
int32 type         # 1：vip；2：drag
string course_name
int32 date_time
int32 tool_num

Vip_Course_Node[] nodes

================================================================================
MSG: rm_healthcare_robot_msgs/Vip_Course_Node
int32 acupoint_id
string acupoint_name
float32[7] pose     # x y z, x y z w
int32 technique_id
int32 time
int32 strength
int32 temp
int32 speed"""
  __slots__ = ['cmd','course_label','old_course_name','keynote_course','vip_course']
  _slot_types = ['string','string','string','rm_healthcare_robot_msgs/Keynote_Course','rm_healthcare_robot_msgs/Vip_Course']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cmd,course_label,old_course_name,keynote_course,vip_course

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Operate_CourseRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cmd is None:
        self.cmd = ''
      if self.course_label is None:
        self.course_label = ''
      if self.old_course_name is None:
        self.old_course_name = ''
      if self.keynote_course is None:
        self.keynote_course = rm_healthcare_robot_msgs.msg.Keynote_Course()
      if self.vip_course is None:
        self.vip_course = rm_healthcare_robot_msgs.msg.Vip_Course()
    else:
      self.cmd = ''
      self.course_label = ''
      self.old_course_name = ''
      self.keynote_course = rm_healthcare_robot_msgs.msg.Keynote_Course()
      self.vip_course = rm_healthcare_robot_msgs.msg.Vip_Course()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.cmd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.course_label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.old_course_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.keynote_course.course_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.keynote_course.date_time, _x.keynote_course.tool_num))
      length = len(self.keynote_course.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.keynote_course.nodes:
        _x = val1.acupoint_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.acupoint_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
      _x = self.vip_course.type
      buff.write(_get_struct_i().pack(_x))
      _x = self.vip_course.course_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.vip_course.date_time, _x.vip_course.tool_num))
      length = len(self.vip_course.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.vip_course.nodes:
        _x = val1.acupoint_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.acupoint_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        buff.write(_get_struct_7f().pack(*val1.pose))
        _x = val1
        buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.keynote_course is None:
        self.keynote_course = rm_healthcare_robot_msgs.msg.Keynote_Course()
      if self.vip_course is None:
        self.vip_course = rm_healthcare_robot_msgs.msg.Vip_Course()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cmd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cmd = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.course_label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.course_label = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.old_course_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.old_course_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.keynote_course.course_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.keynote_course.course_name = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.keynote_course.date_time, _x.keynote_course.tool_num,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.keynote_course.nodes = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Keynote_Course_Node()
        start = end
        end += 4
        (val1.acupoint_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.acupoint_name = str[start:end]
        _x = val1
        start = end
        end += 20
        (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
        self.keynote_course.nodes.append(val1)
      start = end
      end += 4
      (self.vip_course.type,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vip_course.course_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vip_course.course_name = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.vip_course.date_time, _x.vip_course.tool_num,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vip_course.nodes = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Vip_Course_Node()
        start = end
        end += 4
        (val1.acupoint_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.acupoint_name = str[start:end]
        start = end
        end += 28
        val1.pose = _get_struct_7f().unpack(str[start:end])
        _x = val1
        start = end
        end += 20
        (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
        self.vip_course.nodes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.cmd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.course_label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.old_course_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.keynote_course.course_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.keynote_course.date_time, _x.keynote_course.tool_num))
      length = len(self.keynote_course.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.keynote_course.nodes:
        _x = val1.acupoint_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.acupoint_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
      _x = self.vip_course.type
      buff.write(_get_struct_i().pack(_x))
      _x = self.vip_course.course_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.vip_course.date_time, _x.vip_course.tool_num))
      length = len(self.vip_course.nodes)
      buff.write(_struct_I.pack(length))
      for val1 in self.vip_course.nodes:
        _x = val1.acupoint_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.acupoint_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        buff.write(val1.pose.tostring())
        _x = val1
        buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.keynote_course is None:
        self.keynote_course = rm_healthcare_robot_msgs.msg.Keynote_Course()
      if self.vip_course is None:
        self.vip_course = rm_healthcare_robot_msgs.msg.Vip_Course()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cmd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.cmd = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.course_label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.course_label = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.old_course_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.old_course_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.keynote_course.course_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.keynote_course.course_name = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.keynote_course.date_time, _x.keynote_course.tool_num,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.keynote_course.nodes = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Keynote_Course_Node()
        start = end
        end += 4
        (val1.acupoint_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.acupoint_name = str[start:end]
        _x = val1
        start = end
        end += 20
        (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
        self.keynote_course.nodes.append(val1)
      start = end
      end += 4
      (self.vip_course.type,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vip_course.course_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.vip_course.course_name = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.vip_course.date_time, _x.vip_course.tool_num,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.vip_course.nodes = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Vip_Course_Node()
        start = end
        end += 4
        (val1.acupoint_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.acupoint_name = str[start:end]
        start = end
        end += 28
        val1.pose = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
        _x = val1
        start = end
        end += 20
        (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
        self.vip_course.nodes.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/Operate_CourseResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class Operate_CourseResponse(genpy.Message):
  _md5sum = "182deb49b7e799d80643d3eea3be462e"
  _type = "rm_healthcare_robot_msgs/Operate_CourseResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
# 

Standard_Course[] list_standard_course    #如果获取的是标准课程，则对这个数组进行赋值   

Keynote_Course[] list_keynote         # 如果获取的是重点课程

Vip_Course[] list_vip                  # vip课程

int32 state                                # -1:失败；0:成功；1：已有课程；2：     






================================================================================
MSG: rm_healthcare_robot_msgs/Standard_Course
string course_name
string course_brief
string course_pic_path
================================================================================
MSG: rm_healthcare_robot_msgs/Keynote_Course
string course_name
int32 date_time
int32 tool_num

Keynote_Course_Node[] nodes

================================================================================
MSG: rm_healthcare_robot_msgs/Keynote_Course_Node
int32 acupoint_id
string acupoint_name
int32 technique_id
int32 time
int32 strength
int32 temp
int32 speed
================================================================================
MSG: rm_healthcare_robot_msgs/Vip_Course
# 仅用于vip课程中拖动定位课程
int32 type         # 1：vip；2：drag
string course_name
int32 date_time
int32 tool_num

Vip_Course_Node[] nodes

================================================================================
MSG: rm_healthcare_robot_msgs/Vip_Course_Node
int32 acupoint_id
string acupoint_name
float32[7] pose     # x y z, x y z w
int32 technique_id
int32 time
int32 strength
int32 temp
int32 speed"""
  __slots__ = ['list_standard_course','list_keynote','list_vip','state']
  _slot_types = ['rm_healthcare_robot_msgs/Standard_Course[]','rm_healthcare_robot_msgs/Keynote_Course[]','rm_healthcare_robot_msgs/Vip_Course[]','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       list_standard_course,list_keynote,list_vip,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Operate_CourseResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.list_standard_course is None:
        self.list_standard_course = []
      if self.list_keynote is None:
        self.list_keynote = []
      if self.list_vip is None:
        self.list_vip = []
      if self.state is None:
        self.state = 0
    else:
      self.list_standard_course = []
      self.list_keynote = []
      self.list_vip = []
      self.state = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.list_standard_course)
      buff.write(_struct_I.pack(length))
      for val1 in self.list_standard_course:
        _x = val1.course_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.course_brief
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.course_pic_path
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.list_keynote)
      buff.write(_struct_I.pack(length))
      for val1 in self.list_keynote:
        _x = val1.course_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2i().pack(_x.date_time, _x.tool_num))
        length = len(val1.nodes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.nodes:
          _x = val2.acupoint_id
          buff.write(_get_struct_i().pack(_x))
          _x = val2.acupoint_name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
      length = len(self.list_vip)
      buff.write(_struct_I.pack(length))
      for val1 in self.list_vip:
        _x = val1.type
        buff.write(_get_struct_i().pack(_x))
        _x = val1.course_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2i().pack(_x.date_time, _x.tool_num))
        length = len(val1.nodes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.nodes:
          _x = val2.acupoint_id
          buff.write(_get_struct_i().pack(_x))
          _x = val2.acupoint_name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          buff.write(_get_struct_7f().pack(*val2.pose))
          _x = val2
          buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
      _x = self.state
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.list_standard_course is None:
        self.list_standard_course = None
      if self.list_keynote is None:
        self.list_keynote = None
      if self.list_vip is None:
        self.list_vip = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list_standard_course = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Standard_Course()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_brief = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_brief = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_pic_path = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_pic_path = str[start:end]
        self.list_standard_course.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list_keynote = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Keynote_Course()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_name = str[start:end]
        _x = val1
        start = end
        end += 8
        (_x.date_time, _x.tool_num,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.nodes = []
        for i in range(0, length):
          val2 = rm_healthcare_robot_msgs.msg.Keynote_Course_Node()
          start = end
          end += 4
          (val2.acupoint_id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.acupoint_name = str[start:end]
          _x = val2
          start = end
          end += 20
          (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
          val1.nodes.append(val2)
        self.list_keynote.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list_vip = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Vip_Course()
        start = end
        end += 4
        (val1.type,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_name = str[start:end]
        _x = val1
        start = end
        end += 8
        (_x.date_time, _x.tool_num,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.nodes = []
        for i in range(0, length):
          val2 = rm_healthcare_robot_msgs.msg.Vip_Course_Node()
          start = end
          end += 4
          (val2.acupoint_id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.acupoint_name = str[start:end]
          start = end
          end += 28
          val2.pose = _get_struct_7f().unpack(str[start:end])
          _x = val2
          start = end
          end += 20
          (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
          val1.nodes.append(val2)
        self.list_vip.append(val1)
      start = end
      end += 4
      (self.state,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.list_standard_course)
      buff.write(_struct_I.pack(length))
      for val1 in self.list_standard_course:
        _x = val1.course_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.course_brief
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.course_pic_path
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.list_keynote)
      buff.write(_struct_I.pack(length))
      for val1 in self.list_keynote:
        _x = val1.course_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2i().pack(_x.date_time, _x.tool_num))
        length = len(val1.nodes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.nodes:
          _x = val2.acupoint_id
          buff.write(_get_struct_i().pack(_x))
          _x = val2.acupoint_name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
      length = len(self.list_vip)
      buff.write(_struct_I.pack(length))
      for val1 in self.list_vip:
        _x = val1.type
        buff.write(_get_struct_i().pack(_x))
        _x = val1.course_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2i().pack(_x.date_time, _x.tool_num))
        length = len(val1.nodes)
        buff.write(_struct_I.pack(length))
        for val2 in val1.nodes:
          _x = val2.acupoint_id
          buff.write(_get_struct_i().pack(_x))
          _x = val2.acupoint_name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          buff.write(val2.pose.tostring())
          _x = val2
          buff.write(_get_struct_5i().pack(_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed))
      _x = self.state
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.list_standard_course is None:
        self.list_standard_course = None
      if self.list_keynote is None:
        self.list_keynote = None
      if self.list_vip is None:
        self.list_vip = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list_standard_course = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Standard_Course()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_brief = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_brief = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_pic_path = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_pic_path = str[start:end]
        self.list_standard_course.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list_keynote = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Keynote_Course()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_name = str[start:end]
        _x = val1
        start = end
        end += 8
        (_x.date_time, _x.tool_num,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.nodes = []
        for i in range(0, length):
          val2 = rm_healthcare_robot_msgs.msg.Keynote_Course_Node()
          start = end
          end += 4
          (val2.acupoint_id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.acupoint_name = str[start:end]
          _x = val2
          start = end
          end += 20
          (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
          val1.nodes.append(val2)
        self.list_keynote.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list_vip = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.Vip_Course()
        start = end
        end += 4
        (val1.type,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.course_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.course_name = str[start:end]
        _x = val1
        start = end
        end += 8
        (_x.date_time, _x.tool_num,) = _get_struct_2i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.nodes = []
        for i in range(0, length):
          val2 = rm_healthcare_robot_msgs.msg.Vip_Course_Node()
          start = end
          end += 4
          (val2.acupoint_id,) = _get_struct_i().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.acupoint_name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.acupoint_name = str[start:end]
          start = end
          end += 28
          val2.pose = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=7)
          _x = val2
          start = end
          end += 20
          (_x.technique_id, _x.time, _x.strength, _x.temp, _x.speed,) = _get_struct_5i().unpack(str[start:end])
          val1.nodes.append(val2)
        self.list_vip.append(val1)
      start = end
      end += 4
      (self.state,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
class Operate_Course(object):
  _type          = 'rm_healthcare_robot_msgs/Operate_Course'
  _md5sum = '5017c4e56dce9771a2161ce238d38d71'
  _request_class  = Operate_CourseRequest
  _response_class = Operate_CourseResponse
