# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/PhysiotherapyRecordHandleRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class PhysiotherapyRecordHandleRequest(genpy.Message):
  _md5sum = "14d2a26662bcbfa61c9be9e69957d48e"
  _type = "rm_healthcare_robot_msgs/PhysiotherapyRecordHandleRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PhysiotherapyRecord physiotherapy_record

================================================================================
MSG: rm_healthcare_robot_msgs/PhysiotherapyRecord
string time
string project_name
uint16 duration
float32 temp
float32 force
string img_path
string customer
string user"""
  __slots__ = ['physiotherapy_record']
  _slot_types = ['rm_healthcare_robot_msgs/PhysiotherapyRecord']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       physiotherapy_record

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PhysiotherapyRecordHandleRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.physiotherapy_record is None:
        self.physiotherapy_record = rm_healthcare_robot_msgs.msg.PhysiotherapyRecord()
    else:
      self.physiotherapy_record = rm_healthcare_robot_msgs.msg.PhysiotherapyRecord()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.physiotherapy_record.time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.physiotherapy_record.project_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H2f().pack(_x.physiotherapy_record.duration, _x.physiotherapy_record.temp, _x.physiotherapy_record.force))
      _x = self.physiotherapy_record.img_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.physiotherapy_record.customer
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.physiotherapy_record.user
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.physiotherapy_record is None:
        self.physiotherapy_record = rm_healthcare_robot_msgs.msg.PhysiotherapyRecord()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.project_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.project_name = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.physiotherapy_record.duration, _x.physiotherapy_record.temp, _x.physiotherapy_record.force,) = _get_struct_H2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.img_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.img_path = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.customer = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.customer = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.user = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.user = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.physiotherapy_record.time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.physiotherapy_record.project_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H2f().pack(_x.physiotherapy_record.duration, _x.physiotherapy_record.temp, _x.physiotherapy_record.force))
      _x = self.physiotherapy_record.img_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.physiotherapy_record.customer
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.physiotherapy_record.user
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.physiotherapy_record is None:
        self.physiotherapy_record = rm_healthcare_robot_msgs.msg.PhysiotherapyRecord()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.time = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.project_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.project_name = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.physiotherapy_record.duration, _x.physiotherapy_record.temp, _x.physiotherapy_record.force,) = _get_struct_H2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.img_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.img_path = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.customer = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.customer = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.physiotherapy_record.user = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.physiotherapy_record.user = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H2f = None
def _get_struct_H2f():
    global _struct_H2f
    if _struct_H2f is None:
        _struct_H2f = struct.Struct("<H2f")
    return _struct_H2f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/PhysiotherapyRecordHandleResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class PhysiotherapyRecordHandleResponse(genpy.Message):
  _md5sum = "236a1afb2d93e62ce3dbc8f2963c166d"
  _type = "rm_healthcare_robot_msgs/PhysiotherapyRecordHandleResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 result_code
string msg
uint16 list_len
PhysiotherapyRecord[] physiotherapy_record_list

================================================================================
MSG: rm_healthcare_robot_msgs/PhysiotherapyRecord
string time
string project_name
uint16 duration
float32 temp
float32 force
string img_path
string customer
string user"""
  __slots__ = ['result_code','msg','list_len','physiotherapy_record_list']
  _slot_types = ['int8','string','uint16','rm_healthcare_robot_msgs/PhysiotherapyRecord[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result_code,msg,list_len,physiotherapy_record_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PhysiotherapyRecordHandleResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.result_code is None:
        self.result_code = 0
      if self.msg is None:
        self.msg = ''
      if self.list_len is None:
        self.list_len = 0
      if self.physiotherapy_record_list is None:
        self.physiotherapy_record_list = []
    else:
      self.result_code = 0
      self.msg = ''
      self.list_len = 0
      self.physiotherapy_record_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.result_code
      buff.write(_get_struct_b().pack(_x))
      _x = self.msg
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.list_len
      buff.write(_get_struct_H().pack(_x))
      length = len(self.physiotherapy_record_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.physiotherapy_record_list:
        _x = val1.time
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.project_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_H2f().pack(_x.duration, _x.temp, _x.force))
        _x = val1.img_path
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.customer
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.user
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.physiotherapy_record_list is None:
        self.physiotherapy_record_list = None
      end = 0
      start = end
      end += 1
      (self.result_code,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.msg = str[start:end]
      start = end
      end += 2
      (self.list_len,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.physiotherapy_record_list = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PhysiotherapyRecord()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.time = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.time = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.project_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.project_name = str[start:end]
        _x = val1
        start = end
        end += 10
        (_x.duration, _x.temp, _x.force,) = _get_struct_H2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.img_path = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.img_path = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.customer = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.customer = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.user = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.user = str[start:end]
        self.physiotherapy_record_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.result_code
      buff.write(_get_struct_b().pack(_x))
      _x = self.msg
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.list_len
      buff.write(_get_struct_H().pack(_x))
      length = len(self.physiotherapy_record_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.physiotherapy_record_list:
        _x = val1.time
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.project_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_H2f().pack(_x.duration, _x.temp, _x.force))
        _x = val1.img_path
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.customer
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.user
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.physiotherapy_record_list is None:
        self.physiotherapy_record_list = None
      end = 0
      start = end
      end += 1
      (self.result_code,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.msg = str[start:end]
      start = end
      end += 2
      (self.list_len,) = _get_struct_H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.physiotherapy_record_list = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PhysiotherapyRecord()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.time = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.time = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.project_name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.project_name = str[start:end]
        _x = val1
        start = end
        end += 10
        (_x.duration, _x.temp, _x.force,) = _get_struct_H2f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.img_path = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.img_path = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.customer = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.customer = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.user = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.user = str[start:end]
        self.physiotherapy_record_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H = None
def _get_struct_H():
    global _struct_H
    if _struct_H is None:
        _struct_H = struct.Struct("<H")
    return _struct_H
_struct_H2f = None
def _get_struct_H2f():
    global _struct_H2f
    if _struct_H2f is None:
        _struct_H2f = struct.Struct("<H2f")
    return _struct_H2f
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
class PhysiotherapyRecordHandle(object):
  _type          = 'rm_healthcare_robot_msgs/PhysiotherapyRecordHandle'
  _md5sum = '2578ddafc58af40b29f16c561bb227fc'
  _request_class  = PhysiotherapyRecordHandleRequest
  _response_class = PhysiotherapyRecordHandleResponse
