# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/WaypointPixelCoorRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class WaypointPixelCoorRequest(genpy.Message):
  _md5sum = "3ea22d13bd1b2a5e69ac15324cdaae82"
  _type = "rm_healthcare_robot_msgs/WaypointPixelCoorRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PixelCoor[4] diagonal_point_coor   # 轮廓左上角、右上角、左下角、右下角的像素坐标
PixelCoor[] acupoint_pixel_coor    # 识别的穴位二维像素坐标数组(需按照指定顺序)
int8 trajectory_type    # 按摩轨迹类型

================================================================================
MSG: rm_healthcare_robot_msgs/PixelCoor
int16 x
int16 y"""
  __slots__ = ['diagonal_point_coor','acupoint_pixel_coor','trajectory_type']
  _slot_types = ['rm_healthcare_robot_msgs/PixelCoor[4]','rm_healthcare_robot_msgs/PixelCoor[]','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       diagonal_point_coor,acupoint_pixel_coor,trajectory_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointPixelCoorRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.diagonal_point_coor is None:
        self.diagonal_point_coor = [rm_healthcare_robot_msgs.msg.PixelCoor() for _ in range(4)]
      if self.acupoint_pixel_coor is None:
        self.acupoint_pixel_coor = []
      if self.trajectory_type is None:
        self.trajectory_type = 0
    else:
      self.diagonal_point_coor = [rm_healthcare_robot_msgs.msg.PixelCoor() for _ in range(4)]
      self.acupoint_pixel_coor = []
      self.trajectory_type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      if len(self.diagonal_point_coor) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.diagonal_point_coor), 'self.diagonal_point_coor')))
      for val1 in self.diagonal_point_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
      length = len(self.acupoint_pixel_coor)
      buff.write(_struct_I.pack(length))
      for val1 in self.acupoint_pixel_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
      _x = self.trajectory_type
      buff.write(_get_struct_b().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.diagonal_point_coor is None:
        self.diagonal_point_coor = None
      if self.acupoint_pixel_coor is None:
        self.acupoint_pixel_coor = None
      end = 0
      self.diagonal_point_coor = []
      for i in range(0, 4):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.diagonal_point_coor.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.acupoint_pixel_coor = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.acupoint_pixel_coor.append(val1)
      start = end
      end += 1
      (self.trajectory_type,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      if len(self.diagonal_point_coor) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.diagonal_point_coor), 'self.diagonal_point_coor')))
      for val1 in self.diagonal_point_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
      length = len(self.acupoint_pixel_coor)
      buff.write(_struct_I.pack(length))
      for val1 in self.acupoint_pixel_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
      _x = self.trajectory_type
      buff.write(_get_struct_b().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.diagonal_point_coor is None:
        self.diagonal_point_coor = None
      if self.acupoint_pixel_coor is None:
        self.acupoint_pixel_coor = None
      end = 0
      self.diagonal_point_coor = []
      for i in range(0, 4):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.diagonal_point_coor.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.acupoint_pixel_coor = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.acupoint_pixel_coor.append(val1)
      start = end
      end += 1
      (self.trajectory_type,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_healthcare_robot_msgs/WaypointPixelCoorResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import rm_healthcare_robot_msgs.msg

class WaypointPixelCoorResponse(genpy.Message):
  _md5sum = "b59f4644d29f393bcdb618197ba56ac7"
  _type = "rm_healthcare_robot_msgs/WaypointPixelCoorResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PixelCoor[] waypoint_pixel_coor    # 轨迹关键点坐标的二位数组

================================================================================
MSG: rm_healthcare_robot_msgs/PixelCoor
int16 x
int16 y"""
  __slots__ = ['waypoint_pixel_coor']
  _slot_types = ['rm_healthcare_robot_msgs/PixelCoor[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       waypoint_pixel_coor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointPixelCoorResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.waypoint_pixel_coor is None:
        self.waypoint_pixel_coor = []
    else:
      self.waypoint_pixel_coor = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.waypoint_pixel_coor)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoint_pixel_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.waypoint_pixel_coor is None:
        self.waypoint_pixel_coor = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoint_pixel_coor = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.waypoint_pixel_coor.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.waypoint_pixel_coor)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoint_pixel_coor:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.waypoint_pixel_coor is None:
        self.waypoint_pixel_coor = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoint_pixel_coor = []
      for i in range(0, length):
        val1 = rm_healthcare_robot_msgs.msg.PixelCoor()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2h().unpack(str[start:end])
        self.waypoint_pixel_coor.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
class WaypointPixelCoor(object):
  _type          = 'rm_healthcare_robot_msgs/WaypointPixelCoor'
  _md5sum = 'e6fa2c7340c1ca8b7686111fd01d776a'
  _request_class  = WaypointPixelCoorRequest
  _response_class = WaypointPixelCoorResponse
